export const IMAGE_ENDPOINT =
  "https://dak6ovdfbyw15.cloudfront.net/img/5/hw-holiday-2024";

export const IMAGES = {
  OPENING_BG: `${IMAGE_ENDPOINT}/opening-bg.png`,
  OPENING_TITLE: `/logo-removed/opening-title.png`,
  OPENING_BTN: `${IMAGE_ENDPOINT}/opening-btn.png`,
  MUSIC_MUTE_BTN: `${IMAGE_ENDPOINT}/music-mute-btn.png`,
  MUSIC_BTN: `${IMAGE_ENDPOINT}/music-btn.png`,
  OPENING_POPUP: `/logo-removed/opening-popup-v2.png`,
  OPENING_POPUP_BG: `${IMAGE_ENDPOINT}/opening-popup-bg-v2.png`,
  OPENING_POPUP_TITLE: `/logo-removed/opening-popup-title-v2.png`,
  OPENING_POPUP_SECTION1_3: `${IMAGE_ENDPOINT}/opening-popup-section1-3.png`,
  OPENING_POPUP_SECTION4: `${IMAGE_ENDPOINT}/opening-popup-section4.png`,
  OPENING_POPUP_BTN: `${IMAGE_ENDPOINT}/opening-popup-btn.png`,
  OPENING_SPARKLE_TOP: `${IMAGE_ENDPOINT}/opening-sparkle-top.png`,
  OPENING_SPARKLE_BOTTOM: `${IMAGE_ENDPOINT}/opening-sparkle-bottom.png`,
  MAP_TITLE: `/logo-removed/map-title.png`,
  MAP_BG: `${IMAGE_ENDPOINT}/holiday-map-v2.png`,
  COLLECTION_TITLE: `${IMAGE_ENDPOINT}/collection-title-v2.png`,
  COLLECTION_JEWELRY_0: `${IMAGE_ENDPOINT}/collection-jewelry-0-v4.png`,
  COLLECTION_JEWELRY_1: `${IMAGE_ENDPOINT}/collection-jewelry-1-v4.png`,
  COLLECTION_JEWELRY_2: `${IMAGE_ENDPOINT}/collection-jewelry-2-v4.png`,
  ROUTE_1: `${IMAGE_ENDPOINT}/route-1.svg`,
  ROUTE_2: `${IMAGE_ENDPOINT}/route-2.svg`,
  ROUTE_3: `${IMAGE_ENDPOINT}/route-3.svg`,
  STEP_SPARKLE: `${IMAGE_ENDPOINT}/step-sparkle.gif`,
  STEP2_SPARKLE: `${IMAGE_ENDPOINT}/step2-sparkle.gif`,
  STEP1_MODAL_CONTENT: `/logo-removed/step1-modal-content.png`,
  STEP1_MODAL_BTN: `${IMAGE_ENDPOINT}/step3-modal-btn-v2.png`,
  STEP1_WALLPAPER_CONTENT: `${IMAGE_ENDPOINT}/step1-wallpaper-content-v2.png`,
  STEP1_WALLPAPER_BTN: `${IMAGE_ENDPOINT}/step1-wallpaper-btn.png`,
  STEP1_WALLPAPER: `/logo-removed/step1-wallpaper-v5.png`,
  STEP2_WALLPAPER: `/logo-removed/step1-wallpaper-v4.png`,
  STEP2_WALLPAPER_CONTENT: `${IMAGE_ENDPOINT}/step2-wallpaper-content-v2.png`,
  STEP2_BEGIN_MODAL_CONTENT: `/logo-removed/step2-begin-modal-v2.png`,
  STEP2_BEGIN_MODAL_BTN: `${IMAGE_ENDPOINT}/step2-begin-modal-btn.png`,
  STEP2_BG: `${IMAGE_ENDPOINT}/step2-bg-v3.gif`,
  STEP2_COMPLETE_MODAL_CONTENT: `/logo-removed/step2-finish-modal-content-v3.png`,
  STEP2_COMPLETE_MODAL_BTN: `${IMAGE_ENDPOINT}/step1-modal-btn.png`,
  STEP3_MODAL_CONTENT: `/logo-removed/step3-modal-content.png`,
  STEP3_MODAL_BTN: `${IMAGE_ENDPOINT}/step3-modal-btn-v2.png`,
  ENVELOPE: `${IMAGE_ENDPOINT}/envelope-v2.png`,
  ENVELOPE_BTN: `${IMAGE_ENDPOINT}/envelope-btn.png`,
  CLOSE_BTN: `${IMAGE_ENDPOINT}/close-btn.png`,
  CARD0: `${IMAGE_ENDPOINT}/card-0-v2.png`,
  CARD1: `/logo-removed/card-1-v3.png`,
  CARD2: `/logo-removed/card-2-v3.png`,
  CARD3: `/logo-removed/card-3-v3.png`,
  CARD1_WITHOUT_SHADOW: `${IMAGE_ENDPOINT}/card-1-v3-without-shadow.png`,
  CARD2_WITHOUT_SHADOW: `${IMAGE_ENDPOINT}/card-2-v3-without-shadow.png`,
  CARD3_WITHOUT_SHADOW: `${IMAGE_ENDPOINT}/card-3-v3-without-shadow.png`,
  SIGNING_CHOOSE_CARD_TITLE: `${IMAGE_ENDPOINT}/signing-choose-card-title.png`,
  SIGNING_CHOOSE_CARD_BTN: `${IMAGE_ENDPOINT}/signing-choose-card-btn.png`,
  SIGNING_TITLE: `${IMAGE_ENDPOINT}/signing-title.png`,
  SIGNING_COMPLETE_TITLE: `${IMAGE_ENDPOINT}/signing-complete-title.png`,
  SIGNING_COMPLETE_BTN: `${IMAGE_ENDPOINT}/signing-complete-btn.png`,
  START_BTN: `${IMAGE_ENDPOINT}/start-btn-v3.png`,
  BACK_BTN: `${IMAGE_ENDPOINT}/back-btn.png`,
};
export const MUSIC = { BG_MUSIC: `${IMAGE_ENDPOINT}/bg-music-v4.mp3` };

export const ENV_TYPES = {
  LOCAL: "local",
  DEV: "dev",
  PROD: "prod",
};
