export default {
  wallpaperContentSx: {
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
    "& .bg-container": {
      width: "100%",
      height: "100vh",
      position: "absolute",
      overflow: "hidden",
      "& .bg-img": {
        width: "100%",
        verticalAlign: "top",
        height: "100vh",
        zIndex: "-1",
        objectFit: "cover",
      },
    },
  },
  modalWallpaperContentSx: {
    position: "relative",
    width: "100vw",
    height: "100vh",
    maxWidth: "400px",
    display: "flex",
    justifyContent: "center",
    margin: "0 auto",
    "& .modal-content": {
      width: "80%",
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, 25%)",
      "&.step1-wallpaper-content": {
        transform: "translate(-50%, -50%)",
      },
    },
    "& .step1-wallpaper-img": {
      width: "48%",
      height: "auto",
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -52%)",
      borderRadius: "16px",
    },
    "& .modal-btn": {
      width: "58%",
      position: "absolute",
      position: "absolute",
      bottom: "50%",
      left: "50%",
      transform: "translate(-50%, 785%)",
      "&.step1-wallpaper-btn": {
        width: "45%",
        transform: "translate(-50%, 475%)",
      },
    },
  },
  closeWallpaperBtnSx: {
    width: "6.5%",
    position: "absolute",
    top: "10.5%",
    right: "6%",
    cursor: "pointer",
  },
};
